language: php

env:
  global:
    - typo3DatabaseHost=localhost typo3DatabaseName=typo3 typo3DatabaseUsername=root typo3DatabasePassword=''

# stages and ordering /w conditions
stages:
  - static checks
  - unit tests
  - functional tests

jobs:
  fast_finish: true
  include:
    - stage: unit tests
      name: "PHP 7.2 T3v8"
      php: 7.2
      env:
        - TYPO3_VERSION=^8
      script: ./Build/Scripts/runTravisTests.sh -s unit
    - name: "PHP 7.3 T3v8"
      php: 7.3
      env:
        - TYPO3_VERSION=^8
      script: ./Build/Scripts/runTravisTests.sh -s unit
    - name: "PHP 7.2 T3v9"
      php: 7.2
      env:
        - TYPO3_VERSION=^9
      script: ./Build/Scripts/runTravisTests.sh -s unit
    - name: "PHP 7.3 T3v9"
      php: 7.3
      env:
        - TYPO3_VERSION=^9
      script: ./Build/Scripts/runTravisTests.sh -s unit
    - stage: functional tests
      name: "PHP 7.2 T3v8"
      php: 7.2
      env:
        - TYPO3_VERSION=^8
      services:
        - mysql
      script: ./Build/Scripts/runTravisTests.sh -s functional
    - name: "PHP 7.3 T3v8"
      php: 7.3
      env:
        - TYPO3_VERSION=^8
      services:
        - mysql
      script: ./Build/Scripts/runTravisTests.sh -s functional
    - name: "PHP 7.2 T3v9"
      php: 7.2
      env:
        - TYPO3_VERSION=^9
      services:
        - mysql
      script: ./Build/Scripts/runTravisTests.sh -s functional
    - name: "PHP 7.3 T3v9"
      php: 7.3
      env:
        - TYPO3_VERSION=^9
      services:
        - mysql
      script: ./Build/Scripts/runTravisTests.sh -s functional
    - stage: static checks
      name: "PHPLint"
      php: 7.2
      script: ./Build/Scripts/runTravisTests.sh -s lint
    - name: "SonarQube"
      php: 7.2
      script: sonar-scanner -Dproject.settings=Build/.sonar_project.properties -Dsonar.verbose=true

# specification of buil environment
dist: bionic
addons:
  apt:
    packages:
      - parallel
  sonarcloud:
    organization: "thucke"
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.sonar/cache
    - .Build/cache
notifications:
  email:
    recipients:
      - github@thucke.de
    on_success: change
    on_failure: change

# Git disable shallow clones
git:
  depth: false
