language: php

php:
  - 7.2
  - 7.3
env:
  global:
    - typo3DatabaseHost=localhost typo3DatabaseName=typo3 typo3DatabaseUsername=root typo3DatabasePassword=''
  jobs:
    - TYPO3_VERSION=^9
    - TYPO3_VERSION=^8

# stages and ordering /w conditions
stages:
  - static_checks
  - name: test
    if: branch = master

jobs:
  fast_finish: true
  include:
    - stage: static_checks
      name: "PHPLint"
      script:
        - >
          echo;
          echo "Running php lint";
          find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
    - name: "SonarQube"
      script:
        - >
          echo;
          echo "Running Sonar";
          sonar-scanner -Dproject.settings=Build/.sonar_project.properties -Dsonar.verbose=true

    - stage: test
      name: "Unit tests"
      script:
        - >
          echo;
          echo "Running unit tests";
          .Build/bin/phpunit --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/
    - name: "Functional tests"
      script:
        - >
          echo;
          echo "Running functional tests";
          find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit --colors  -c .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml {}'

# specification of buil environment
dist: bionic
services:
  - mysql
addons:
  apt:
    packages:
      - parallel
  sonarcloud:
    organization: "thucke"
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.sonar/cache
    - .Build/cache
notifications:
  email:
    recipients:
      - github@thucke.de
    on_success: change
    on_failure: change

# Git disable shallow clones
git:
  depth: false

# preparation of build environment
before_install:
  - composer self-update
  - composer --version

# preparation of script environment
before_script:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - composer require typo3/minimal=$TYPO3_VERSION
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web


