language: php

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: TYPO3_VERSION=^9
    - php: 7.2
      env: TYPO3_VERSION=^8
    - php: 7.3
      env: TYPO3_VERSION=^9
    - php: 7.3
      env: TYPO3_VERSION=^8

sudo: false

addons:
  apt:
    packages:
      - parallel
  sonarcloud:
    organization: "thucke"

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.sonar/cache
    - .Build/cache

notifications:
  email:
    recipients:
      - github@thucke.de
    on_success: change
    on_failure: change

branches:
  except:
    - documentation-draft
    - experimental

env:
  global:
    - typo3DatabaseHost=localhost typo3DatabaseName=typo3 typo3DatabaseUsername=root typo3DatabasePassword=''

before_install:
  - composer self-update
  - composer --version

before_script:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - composer require typo3/minimal=$TYPO3_VERSION
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/

  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

  - >
    echo;
    echo "Running Sonar";
    sonar-scanner -Dproject.settings=Build/.sonar-project.properties

  - >
    echo;
    echo "Running functional tests";
    find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit --colors  -c .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml {}'
