language: php

php:
  - 7.2
  - 7.3
env:
  - TYPO3_VERSION=^9
  - TYPO3_VERSION=^8
  global:
    - typo3DatabaseHost=localhost typo3DatabaseName=typo3 typo3DatabaseUsername=root typo3DatabasePassword=''

# stages and ordering /w conditions
stages:
  - static_checks
  - name: test
    if: branch = master




